# Generated by Django 3.1.3 on 2020-11-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LimitTimeSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('brand', models.TextField()),
                ('title', models.TextField()),
                ('old_price', models.IntegerField()),
                ('discount', models.IntegerField(null=True)),
                ('new_price', models.IntegerField()),
            ],
            options={
                'unique_together': {('begin_time', 'end_time', 'brand', 'title')},
            },
        ),
    ]
