# Generated by Django 3.1.3 on 2020-11-17 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('momoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('discount_date', models.CharField(max_length=100)),
                ('condition', models.CharField(max_length=100)),
                ('discount', models.CharField(max_length=100)),
                ('begin_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='limittimesale',
            name='discount',
            field=models.FloatField(null=True),
        ),
    ]
