# Generated by Django 3.0.6 on 2020-10-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionframework',
            name='title_hash',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
